name: Push DEV to PROD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_prod:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout DEV repo (databricks-test)
      - name: Checkout databricks-test
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Commit & Push to main-repo
      - name: Push to main-repo
        uses: ad-m/github-push-action@v0.6.0
        with:
          repository: databricks-learning-for-capy/main-repo
          branch: main
          github_token: ${{ secrets.REPO_SYNC_TOKEN }}
          force: true
